### ISSUE TITLE
[bug]? Local Xml on card objects.

### ISSUE THREAD

**Issue by Jophire** [Berserk-Games/Tabletop-Simulator-API#53]
Xml on card objects blocks picking up the card, but will not trigger event attributes when interacted with if the card is selectable.

Test Script:
```
--Card XML
function onLoad(sd)
  flip = -1  -- 1 is face up, -1 is face down.
  scaler = {x=1,y=1,z=1}--o.getScale()
  zpos = -26*flip*scaler.z
  --Cards have always had weird up and foward vectors, making decals and xml function weird.
--]]..tostring(90-90*flip)..[[
  card_xml = [[                                                                             
  <Panel id="Encoder_Card" version='0' active="true" position="0 0 ]]..zpos..[[" rotation="180 0 0">
    <Button id="PropButt" 
      onClick="]]..self.guid..[[/buttonClick(PropList)" 
      position="-104 0 0" 
      width='10' height='300' 
      colors='Black|Grey|White|Red'
      raycastTarget='True'>Properties</Button>
    <Panel id="PropList"  visibility='Safety' position="140 10 0" width="60" height="290" color="rgba(1 1 1 0.5)">
    </Panel>
  </Panel>]]
  Wait.frames(function() self.UI.setXml(card_xml) end, 1)
end
  
function buttonClick(p,val,id)
  print(id..":"..val..":"..p.color)
  if id == 'PropButt' then
    toggleVisibility(val,p.color)
  end 
end

function toggleVisibility(id,pl)
  --XML helper function, takes xml id and player color
  colors, count = string.gsub(self.UI.getAttribute(id,"visibility"),"|?"..pl,"")
  colors = triml(colors,'|')
  if count > 0 then
    self.UI.setAttribute(id,"visibility",colors)
  else
    if colors == "" then
      self.UI.setAttribute(id,"visibility","Safety|"..pl)
    else
      self.UI.setAttribute(id,"visibility",colors.."|"..pl)
    end
  end
  --print(id..':'..self.UI.getAttribute(id,"visibility"))
end
function triml(s,c)
  return string.gsub(s,"^"..c.."*","")
end
```
--There is a tiny sliver of button that can be clicked without highlighting the card behind it that will function.

**Comment by AufderWelt** [comment]
hi, tried it, was not able to reproduce it, maybe it is fixed?

**Comment by Jophire** [comment]
I am still having problems with unexpected behavior when applying XML to custom card objects, the biggest of which is that custom Cards render upside down when compared to XML.

```
<Panel id="" active="true" visibilty="" version="" width="0" height="0" position="120 -60 -28" rotation="180 180 0">
        <Button id="MenuBut" onClick="]]..g..[[/toggle" width="60" height="20" color="white" rotation="0 0 90" fontStyle="bold" fontSize="15">Open</Button>
        <Panel id="Droplist" active="true" height="700" width="200" position="-115 0" color="red">
          <Text position="0 335">Property List</Text>
        </Panel>
        </Panel>
```
Notice the rotation needed to make sure the XML is facing the right direction in regards to a faceup custom card.
However, when you try and add a VerticalScrollView, it will not display correctly as long as the rotation is not {0 0 0}.
Buttons are also finicky due to the rotation.

**Comment by nabbydude** [comment]
Looks like your issue pertains to Tabletop Simulator itself, and not the API documentation, which this repo is for. Check out [https://tabletopsimulator.nolt.io/](https://tabletopsimulator.nolt.io/) to submit and vote for bugs, suggestions, and requests for the game itself. If you just have a question about the game, also check out [The Official Tabletop Simulator Discord Server](https://discord.com/invite/tabletopsimulator), the community may be able to answer it.
